// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCny7yrzEVPHW60BTpWT2jW2MHigwhQWdk',
    appId: '1:676691628959:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '676691628959',
    projectId: 'mentalhealth-project-a1809',
    storageBucket: 'mentalhealth-project-a1809.firebasestorage.app',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCny7yrzEVPHW60BTpWT2jW2MHigwhQWdk',
    appId: '1:676691628959:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '676691628959',
    projectId: 'mentalhealth-project-a1809',
    storageBucket: 'mentalhealth-project-a1809.firebasestorage.app',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCny7yrzEVPHW60BTpWT2jW2MHigwhQWdk",
    authDomain: "mentalhealth-project-a1809.firebaseapp.com",
    projectId: "mentalhealth-project-a1809",
    storageBucket: "mentalhealth-project-a1809.firebasestorage.app",
    messagingSenderId: "676691628959",
    appId: "1:676691628959:web:da00beaa686def045c63aa",
    measurementId: "G-BBBMYY141M",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9vL63-RqX2v_AeL5FrRIL1xwGCoz476I',
    appId: '1:676691628959:android:6507c318952a445a5c63aa',
    messagingSenderId: '676691628959',
    projectId: 'mentalhealth-project-a1809',
    storageBucket: 'mentalhealth-project-a1809.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyCny7yrzEVPHW60BTpWT2jW2MHigwhQWdk",
    authDomain: "mentalhealth-project-a1809.firebaseapp.com",
    projectId: "mentalhealth-project-a1809",
    storageBucket: "mentalhealth-project-a1809.firebasestorage.app",
    messagingSenderId: "676691628959",
    appId: "1:676691628959:web:66dfd6f1d67cc7035c63aa",
    measurementId: "G-VCFEZXS4ZT",
  );
}
